### ISSUE TITLE
trouble getting the mw.xml_dump.Iterator to work

### ISSUE THREAD

**Issue by peeter-t2** [mediawiki-utilities/python-mediawiki-utilities#42]
Great script! 
I tried to follow the guide http://pythonhosted.org/mediawiki-utilities/core/xml_dump.html#mw-xml-dump to access a local wikipedia dump.

I just copied the iterator code

```
from mw.xml_dump import Iterator

# Construct dump file iterator
dump = Iterator.from_file(open("example/dump.xml"))

# Iterate through pages
for page in dump:

    # Iterate through a page's revisions
    for revision in page:

        print(revision.id)
```

However, this gives me the following error. I also tried to install multiprocessing, but for no difference. Any ideas what could be the problem?

Traceback (most recent call last):
  File "/home/user/Downloads/mw_dump_iterator.py", line 3, in <module>
    from mw.xml_dump import Iterator
  File "/usr/local/lib/python2.7/dist-packages/mw/xml_dump/**init**.py", line 25, in <module>
    from .map import map
  File "/usr/local/lib/python2.7/dist-packages/mw/xml_dump/map.py", line 3, in <module>
    from queue import Empty
ImportError: No module named queue

Thanks!

**Comment by peeter-t2** [comment]
PS Same error with the simple iterator too.

```
from mw import xml_dump

files = ["examples/dump.xml", "examples/dump2.xml"]

def page_info(dump, path):
    for page in dump:

        yield page.id, page.namespace, page.title


for page_id, page_namespace, page_title in xml_dump.map(files, page_info):
    print(" ".join([str(page_id), str(page_namespace), page_title]))
```

**Comment by peeter-t2** [comment]
Found a remark on SO http://stackoverflow.com/questions/3463447/parsing-a-wikipedia-dump that I must have missed elsewhere. It says `mw` works only with Python 3+. True? This is the problem then, as I was on Python 2.7.

**Comment by peeter-t2** [comment]
Confirmed, that this is indeed the problem. Py 3.5 works.
